paytm.payment:
  sandbox:
    merchantId: hByKmr91351604741532
    merchantKey: eR4SYdNzSRC44k#K
    channelId: WEB
    website: WEBSTAGING
    industryTypeId: Retail
    paytmUrl:  https://securegw-stage.paytm.in/order/process
    callbackUrl: http://localhost:8094/paymentresponse
    details:
      MID: ${paytm.payment.sandbox.merchantid}
      CHANNEL_ID: ${paytm.payment.sandbox.channelid}
      INDUSTRY_TYPE_ID: ${paytm.payment.sandbox.industrytypeid}
      WEBSITE: ${paytm.payment.sandbox.website}
      CALLBACK_URL: ${paytm.payment.sandbox.callbackUrl}